<?php

	// BUILD REPORT


	// build raw string
	$raw = '';
	$raw .= '<style> 

				#header_logo {
					position:relative;
					top:10px;
					left:50px;
					width:50px;
					height:50px;
					padding-top: 7px;
					padding-left:125px;

				}

				#header_title {
					position:fixed;
					top:0;
					left:0;
					width:100%;
					height:70px;
					border-bottom: 1px solid black;
					text-align: center;
					font-size: 30px;
					line-height: 70px;
				}

				#map {
					margin-top: 30px;
					margin-bottom: 20px;
				}

				#map, #map img {
					text-align: center;
				}
				
				#layers {
					font-size: 10px;
					display:inline;
				}


				#legend {
					font-size: 10px;
				}

				.field {
					font-size: 12px;
					margin: 20px;
				}
				
				#license, #license p, #license p a {
					font-size: 8px
				}
				
				#footer {
					border-top: 1px solid black;
					margin-top:20px;
					padding: 10px;
					text-align: center;
					font-size: 10px;
				}
			</style>';

	// add header
	// $raw .= '<div id="header">';
	$raw .= '<div id="header_logo"><img src="http://labs.aiddata.org/aiddata/imgs/ccblogo_square_notext.jpg"></div>';
	$raw .= '<div id="header_title">CCB Mapping Portal</div>';
	// $raw .= '</div>';

	// add map image
	$raw .= '<div id="map"><img height="500px" src="'.$TEMP_DIR.'/'.$TEMP_URL.'.jpg'.'"/></div>';




	// add legend if it exists
	// if ( count($_POST['legend']) > 0 ) {
	// 	$raw .= '<div id="legend"><b>Active Legend ('.$_POST['active'].'): </b>';
	// 		$raw .= '<ul>';
	// 		foreach ($_POST['legend'] as $legend_item) {
	// 			$raw .= '<li style="color:'.$legend_item[1].'">'.$legend_item[0].'</li>';
	// 		}
	// 		$raw .= '</ul>';
	// 	$raw .= '</div>';
	// }


	// add active layers
	$raw .= '<div class="field"><b>Layers: </b>';
		$c = 0;
		foreach ($_POST['layers'] as $active_layer) {
			if ($c != 0) {
				$raw .= ', ';
			}
			$raw .= $active_layer;
			$c+=1;
		}
	$raw .= '</div>';


	// add center coordinates
	$raw .= '<div class="field"><b>Map Center: </b>['.$_POST['centerlng'].', '.$_POST['centerlat'].']</div>';

	// add link
	$raw .= '<div class="field"><b>Map Link: </b><a href="'.$_POST['link'].'">'.$_POST['link'].'</a></div>';

	// add export date
	$raw .= '<div class="field"><b>Report Generated On: </b>'.date('m/d/Y').'</div>';


	$license_text = '<p>The Center for Conservation Biology (CCB) provides certain data online as a free service to the public and the
					regulatory sector. CCB encourages the use of its data sets in wildlife conservation and management applications. 
					These data are protected by intellectual property laws. All users are reminded to view the 
					<a href="http://www.ccbbirds.org/resources/data-use-agreement/">Data Use Agreement</a> to 
					ensure compliance with our data use policies. For additional data access questions, view our 
					<a href="http://www.ccbbirds.org/resources/data-distribution-policy/">Data Distribution Policy</a>, 
					or contact our Data Manager, Marie Pitts, at mlpitts@wm.edu or 757-221-7503.</p>';


	$footer_text = '<p>Report generated by <a href="http://www.ccbbirds.org/maps/">The Center for Conservation Biology Mapping Portal</a>.</p>
				  	<p>To learn more about CCB visit <a href="http://www.ccbbirds.org">ccbbirds.org</a> or contact us at info@ccbbirds.org</p>';

	// add license info
	$raw .= '<div id="license">'.$license_text.'</div>';

	// add footer
	$raw .= '<div id="footer">'.$footer_text.'</div>';

?>
